spring.application.name=demo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/personal_finance
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# OpenAPI / Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
app.jwt.secret=If0cBnl6lwe4hO5Piv8/OoF3q/C2HZFYNIjSPL7yjdg=
app.jwt.expiration-ms=86400000
